version: '3'

tasks:
  build:
    deps: [build-debug, build-release]

  doc:
    cmds:
      - cargo doc

  build-debug:
    cmds:
      - cargo build --no-default-features -Fqemu,defmt

  build-release:
    cmds:
      - cargo build --release --no-default-features -Fqemu,defmt

  start-mqtt:
    cmds:
      - rumqttd -c rumqttd.toml --quiet

  setup-tap:
    silent: true
    cmds:
      - |
          ip link show tap0 > /dev/null && exit 0 || true;
           sudo ip tuntap add tap0 mode tap user $USER ;
           sudo ip addr flush dev tap0 ;
      - task: setup-link-tap0

  remove-tap:
    cmds:
      - sudo ip tuntap del tap0 mode tap

  setup-link-*:
    silent: true
    vars:
      DEV: '{{ index .MATCH 0 }}'
      MQTT_IP_V4:
        sh: awk -F "=" '/^MQTT_BROKER_IP/ { gsub(/"/, "", $2); print $2 }' .cargo/config.toml | tr -d " "
      GATEWAY_IP_V4:
        sh: awk -F "=" '/^IP_V4_GATEWAY/ { gsub(/"/, "", $2); print $2 }' .cargo/config.toml | tr -d " "
      GATEWAY_IP_V6:
        sh: awk -F "=" '/^IP_V6_GATEWAY/ { gsub(/"/, "", $2); print $2 }' .cargo/config.toml | tr -d " "
    cmds:
      - echo "Setting up link {{.DEV}} with IPs {{.MQTT_IP_V4}}, {{.GATEWAY_IP_V4}}, {{.GATEWAY_IP_V6}}"
      - |
           sudo ip link set {{.DEV}} up ;
           sudo ip addr add {{.MQTT_IP_V4}}/24 dev {{.DEV}} ; # mqtt broker
           sudo ip addr add {{.GATEWAY_IP_V4}}/24 dev {{.DEV}} ; # this device
           sudo ip -6 addr add {{.GATEWAY_IP_V6}}/64 dev {{.DEV}} ;
           sudo ip -6 route add {{.GATEWAY_IP_V6}}/64 dev {{.DEV}} ;

  run-debug-qemu:
    deps: [build-debug]
    cmds:
      - task: run-qemu
        vars: { PROFILE: 'debug' }

  run-release-qemu:
    deps: [build-release]
    cmds:
      - task: run-qemu
        vars: { PROFILE: 'release' }

  run-qemu:
    internal: true
    deps: [build-debug]
    vars:
      PROFILE: '{{ default "-" .PROFILE }}'
      TARGET:
        sh: awk -F "=" '/^target/ { gsub(/"/, "", $2); print $2 }' .cargo/config.toml | tr -d " "
      MAC:
        sh: awk -F "=" '/^MAC/ { gsub(/"/, "", $2); print $2 }' .cargo/config.toml | tr -d " "

    cmds:
      - task: setup-tap
      - cmd: if [ "{{.PROFILE}}" == "-" ]; then echo "PROFILE is not set"; exit 1; fi
        silent: true
      # - qemu-system-arm
      - /home/ddystopia/job/qemu/build/qemu-system-arm
        -cpu cortex-m3
        -machine lm3s6965evb
        -display none
        -nographic
        -serial mon:stdio
        -net nic,macaddr={{.MAC}}
        -net tap,ifname=tap0,script=no,downscript=no
        -semihosting-config enable=on,target=native
        -kernel target/{{.TARGET}}/{{.PROFILE}}/project
        -gdb tcp::1234
        | defmt-print -v -e target/{{.TARGET}}/{{.PROFILE}}/project
