#![no_std]

// Acknowledgement:
// https://github.com/nghiaducnt/LearningRIOT/tree/2019.01-my/cpu/cc2538/stellaris_ether

#[unsafe(no_mangle)]
extern "C" fn __lm3s6965evb_ethernet_assert(
    value: core::ffi::c_uchar,
    func: *const u8,
    file: *const u8,
    line: core::ffi::c_ulong,
) {
    if value == 0 {
        if file.is_null() || func.is_null() {
            panic!("Assertion failed at unknown location at line {}", line);
        }
        let file = unsafe { core::ffi::CStr::from_ptr(file) };
        let func = unsafe { core::ffi::CStr::from_ptr(func) };
        let (Ok(file), Ok(func)) = (file.to_str(), func.to_str()) else {
            panic!("Assertion failed at unknown location at line {}", line);
        };

        panic!("Assertion failed in {func} at {file}:{line}")
    }
}

mod raw {
    #![allow(non_camel_case_types)]
    #![allow(non_upper_case_globals)]
    #![allow(unused)]

    use core::{concat, env, include};

    include!(concat!(env!("OUT_DIR"), "/ethernet.rs"));
}

pub use raw::{
    ETH_BASE, ETH_CFG_RX_AMULEN, ETH_CFG_RX_BADCRCDIS, ETH_CFG_RX_PRMSEN, ETH_CFG_TS_TSEN,
    ETH_CFG_TX_CRCEN, ETH_CFG_TX_DPLXEN, ETH_CFG_TX_PADEN, ETH_INT_MDIO, ETH_INT_PHY, ETH_INT_RX,
    ETH_INT_RXER, ETH_INT_RXOF, ETH_INT_TX, ETH_INT_TXER,
};

pub use raw::{
    EthernetConfigGet, EthernetConfigSet, EthernetDisable, EthernetEnable, EthernetInitExpClk,
    EthernetIntClear, EthernetIntDisable, EthernetIntEnable, EthernetIntRegister,
    EthernetIntStatus, EthernetIntUnregister, EthernetMACAddrGet, EthernetMACAddrSet,
    EthernetPHYAddrSet, EthernetPHYPowerOff, EthernetPHYPowerOn, EthernetPHYRead, EthernetPHYWrite,
    EthernetPacketAvail, EthernetPacketGet, EthernetPacketGetNonBlocking, EthernetPacketPut,
    EthernetPacketPutNonBlocking, EthernetSpaceAvail,
};

pub use raw::{
    MAC_BASE, MAC_DATA_RXDATA_M, MAC_DATA_RXDATA_S, MAC_DATA_TXDATA_M, MAC_DATA_TXDATA_S,
    MAC_IA0_MACOCT1, MAC_IA0_MACOCT1_M, MAC_IA0_MACOCT1_S, MAC_IA0_MACOCT2, MAC_IA0_MACOCT2_M,
    MAC_IA0_MACOCT2_S, MAC_IA0_MACOCT3, MAC_IA0_MACOCT3_M, MAC_IA0_MACOCT3_S, MAC_IA0_MACOCT4,
    MAC_IA0_MACOCT4_M, MAC_IA0_MACOCT4_S, MAC_IA1_MACOCT5, MAC_IA1_MACOCT5_M, MAC_IA1_MACOCT5_S,
    MAC_IA1_MACOCT6, MAC_IA1_MACOCT6_M, MAC_IA1_MACOCT6_S, MAC_IACK_FOV, MAC_IACK_MDINT,
    MAC_IACK_PHYINT, MAC_IACK_RXER, MAC_IACK_RXINT, MAC_IACK_TXEMP, MAC_IACK_TXER, MAC_IM_FOVM,
    MAC_IM_MDINTM, MAC_IM_PHYINTM, MAC_IM_RXERM, MAC_IM_RXINTM, MAC_IM_TXEMPM, MAC_IM_TXERM,
    MAC_IS_FOV, MAC_IS_MDINT, MAC_IS_PHYINT, MAC_IS_RXER, MAC_IS_RXINT, MAC_IS_TXEMP, MAC_IS_TXER,
    MAC_LED_LED0_10, MAC_LED_LED0_100, MAC_LED_LED0_DUPLEX, MAC_LED_LED0_LINK,
    MAC_LED_LED0_LINKACT, MAC_LED_LED0_M, MAC_LED_LED0_RXTX, MAC_LED_LED1_10, MAC_LED_LED1_100,
    MAC_LED_LED1_DUPLEX, MAC_LED_LED1_LINK, MAC_LED_LED1_LINKACT, MAC_LED_LED1_M,
    MAC_LED_LED1_RXTX, MAC_MADD_PHYADR_M, MAC_MADD_PHYADR_S, MAC_MCTL_REGADR, MAC_MCTL_REGADR_M,
    MAC_MCTL_REGADR_S, MAC_MCTL_START, MAC_MCTL_WRITE, MAC_MDIX_EN, MAC_MDV_DIV, MAC_MDV_DIV_M,
    MAC_MDV_DIV_S, MAC_MRXD_MDRX, MAC_MRXD_MDRX_M, MAC_MRXD_MDRX_S, MAC_MTXD_MDTX, MAC_MTXD_MDTX_M,
    MAC_MTXD_MDTX_S, MAC_NP_NPR, MAC_NP_NPR_M, MAC_NP_NPR_S, MAC_O_DATA, MAC_O_IA0, MAC_O_IA1,
    MAC_O_IACK, MAC_O_IM, MAC_O_IS, MAC_O_LED, MAC_O_MADD, MAC_O_MCTL, MAC_O_MDIX, MAC_O_MDV,
    MAC_O_MRXD, MAC_O_MTXD, MAC_O_NP, MAC_O_RCTL, MAC_O_RIS, MAC_O_TCTL, MAC_O_THR, MAC_O_TR,
    MAC_O_TS, MAC_RCTL_AMUL, MAC_RCTL_BADCRC, MAC_RCTL_PRMS, MAC_RCTL_RSTFIFO, MAC_RCTL_RXEN,
    MAC_RIS_FOV, MAC_RIS_MDINT, MAC_RIS_PHYINT, MAC_RIS_RXER, MAC_RIS_RXINT, MAC_RIS_TXEMP,
    MAC_RIS_TXER, MAC_RV_DATA, MAC_RV_IA0, MAC_RV_IA1, MAC_RV_IACK, MAC_RV_IM, MAC_RV_IS,
    MAC_RV_MADD, MAC_RV_MCTL, MAC_RV_MDV, MAC_RV_MRXD, MAC_RV_MTXD, MAC_RV_NP, MAC_RV_RCTL,
    MAC_RV_TCTL, MAC_RV_THR, MAC_RV_TR, MAC_TCTL_CRC, MAC_TCTL_DUPLEX, MAC_TCTL_PADEN,
    MAC_TCTL_TXEN, MAC_THR_THRESH, MAC_THR_THRESH_M, MAC_THR_THRESH_S, MAC_TR_NEWTX, MAC_TS_TSEN,
    PHY_MR0, PHY_MR0_ANEGEN, PHY_MR0_COLT, PHY_MR0_DUPLEX, PHY_MR0_ISO, PHY_MR0_LOOPBK,
    PHY_MR0_PWRDN, PHY_MR0_RANEG, PHY_MR0_RESET, PHY_MR0_SPEEDSL, PHY_MR1, PHY_MR1_10T_F,
    PHY_MR1_10T_H, PHY_MR1_100X_F, PHY_MR1_100X_H, PHY_MR1_ANEGA, PHY_MR1_ANEGC, PHY_MR1_EXTD,
    PHY_MR1_JAB, PHY_MR1_LINK, PHY_MR1_MFPS, PHY_MR1_RFAULT, PHY_MR2, PHY_MR2_OUI_M, PHY_MR2_OUI_S,
    PHY_MR3, PHY_MR3_MN_M, PHY_MR3_MN_S, PHY_MR3_OUI_M, PHY_MR3_OUI_S, PHY_MR3_RN_M, PHY_MR3_RN_S,
    PHY_MR4, PHY_MR4_A0, PHY_MR4_A1, PHY_MR4_A2, PHY_MR4_A3, PHY_MR4_NP, PHY_MR4_RF, PHY_MR4_S_M,
    PHY_MR4_S_S, PHY_MR5, PHY_MR5_A_M, PHY_MR5_A_S, PHY_MR5_ACK, PHY_MR5_NP, PHY_MR5_RF,
    PHY_MR5_S_1394, PHY_MR5_S_8023, PHY_MR5_S_8025, PHY_MR5_S_8029, PHY_MR5_S_M, PHY_MR6,
    PHY_MR6_LPANEGA, PHY_MR6_LPNPA, PHY_MR6_PDF, PHY_MR6_PRX, PHY_MR16, PHY_MR16_APOL,
    PHY_MR16_INPOL, PHY_MR16_NL10, PHY_MR16_PCSBP, PHY_MR16_RPTR, PHY_MR16_RVSPOL, PHY_MR16_RXCC,
    PHY_MR16_SQEI, PHY_MR16_SR_M, PHY_MR16_SR_S, PHY_MR16_TXHIM, PHY_MR17, PHY_MR17_ANEGCOMP_IE,
    PHY_MR17_ANEGCOMP_INT, PHY_MR17_EDPD, PHY_MR17_ENON, PHY_MR17_FASTEST, PHY_MR17_FASTRIP,
    PHY_MR17_FGLS, PHY_MR17_JABBER_IE, PHY_MR17_JABBER_INT, PHY_MR17_LPACK_IE, PHY_MR17_LPACK_INT,
    PHY_MR17_LSCHG_IE, PHY_MR17_LSCHG_INT, PHY_MR17_LSQE, PHY_MR17_PDF_IE, PHY_MR17_PDF_INT,
    PHY_MR17_PRX_IE, PHY_MR17_PRX_INT, PHY_MR17_RFAULT_IE, PHY_MR17_RFAULT_INT, PHY_MR17_RXER_IE,
    PHY_MR17_RXER_INT, PHY_MR18, PHY_MR18_ANEGF, PHY_MR18_DPLX, PHY_MR18_RATE, PHY_MR18_RX_LOCK,
    PHY_MR18_RXSD, PHY_MR19, PHY_MR19_TXO_00DB, PHY_MR19_TXO_04DB, PHY_MR19_TXO_08DB,
    PHY_MR19_TXO_12DB, PHY_MR19_TXO_M, PHY_MR23, PHY_MR23_LED0_10, PHY_MR23_LED0_100,
    PHY_MR23_LED0_COL, PHY_MR23_LED0_DUPLEX, PHY_MR23_LED0_LINK, PHY_MR23_LED0_LINKACT,
    PHY_MR23_LED0_M, PHY_MR23_LED0_RX, PHY_MR23_LED0_RXTX, PHY_MR23_LED0_TX, PHY_MR23_LED1_10,
    PHY_MR23_LED1_100, PHY_MR23_LED1_COL, PHY_MR23_LED1_DUPLEX, PHY_MR23_LED1_LINK,
    PHY_MR23_LED1_LINKACT, PHY_MR23_LED1_M, PHY_MR23_LED1_RX, PHY_MR23_LED1_RXTX, PHY_MR23_LED1_TX,
    PHY_MR24, PHY_MR24_AUTO_SW, PHY_MR24_MDIX, PHY_MR24_MDIX_CM, PHY_MR24_MDIX_SD_M,
    PHY_MR24_MDIX_SD_S, PHY_MR24_PD_MODE, PHY_MR27, PHY_MR27_XPOL, PHY_MR29, PHY_MR29_ANCOMPIS,
    PHY_MR29_EONIS, PHY_MR29_LDIS, PHY_MR29_LPACKIS, PHY_MR29_PDFIS, PHY_MR29_PRXIS,
    PHY_MR29_RFLTIS, PHY_MR30, PHY_MR30_ANCOMPIM, PHY_MR30_EONIM, PHY_MR30_LDIM, PHY_MR30_LPACKIM,
    PHY_MR30_PDFIM, PHY_MR30_PRXIM, PHY_MR30_RFLTIM, PHY_MR31, PHY_MR31_AUTODONE, PHY_MR31_SCRDIS,
    PHY_MR31_SPEED_10FD, PHY_MR31_SPEED_10HD, PHY_MR31_SPEED_100FD, PHY_MR31_SPEED_100HD,
    PHY_MR31_SPEED_M,
};
