[build]
# target = "thumbv7em-none-eabihf"
target = "thumbv7em-none-eabi"

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "target-cpu=cortex-m4",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[target.thumbv7em-none-eabi]
rustflags = [
  "-C", "target-cpu=cortex-m3",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # "-Z", "location-detail=none", # for some reason increases the size
  # "-Z", "fmt-debug=none",
]

# [unstable]
# build-std = ["core", "panic_abort"]
# build-std-features = ["optimize_for_size", "panic_immediate_abort"]

[env]
CC = "/home/ddystopia/code/ra6m3-rtic/toolchain_m3/arm-bare_newlibnanolto_cortex_m3-eabi/bin/arm-bare_newlibnanolto_cortex_m3-eabi-gcc"
DEFMT_LOG = "trace,smoltcp=info,embedded_tls=info"
MAC = "fe:e3:a9:97:ad:ab"
IP_V4 = "192.168.69.100/24"
IP_V4_GATEWAY = "192.168.69.1"
IP_V6 = "fdaa:0000:0000:0000:0000:0000:0000:100/64"
IP_V6_GATEWAY = "fdaa:0000:0000:0000:0000:0000:0000:1"
MQTT_CLIENT_ID = "rtic"
MQTT_BROKER_IP = "192.168.69.20"
MQTT_BROKER_PORT = "8883" # uncomment for tls
# MQTT_BROKER_PORT = "1883" # uncomment for non-tls
