#ifndef R_ETHER_PHY_CFG_H__
#define R_ETHER_PHY_CFG_H__

#define ETHER_PHY_CFG_PARAM_CHECKING_ENABLE     1

#define ETHER_PHY_CFG_TARGET_KSZ8091RNB_ENABLE  1
#define ETHER_PHY_CFG_TARGET_KSZ8041_ENABLE     0
#define ETHER_PHY_CFG_TARGET_DP83620_ENABLE     0
#define ETHER_PHY_CFG_TARGET_ICS1894_ENABLE     0

#define ETHER_PHY_CFG_USE_REF_CLK               (BOARD_PHY_REF_CLK)

#endif /* R_ETHER_PHY_CFG_H__ */
